name: Generate README.md for each directory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Generate README.md
        run: |
          node .github/scripts/generate-readme.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Check for changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update README.md files"
            git push
          else
            echo "No changes found to commit."
          fi
